# Generated by Django 3.1.5 on 2021-04-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
